apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumeai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: resume-analyser-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
            #Expose Ray Dashboard port
            - containerPort: 8265 
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: resumeai-secret
                  key: GROQ_API_KEY
          
          #Give Ray enough CPU cores to actually run in parallel
          resources:
            requests:
              cpu: "2"       # Request at least 2 cores
              memory: "2Gi"
            limits:
              cpu: "4"       # Allow up to 4 cores
              memory: "4Gi"
              
          #Mount the shared memory volume to the container
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm

      #Define the shared memory volume (Memory-backed emptyDir)
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory